apiVersion: v1
kind: PersistentVolume
metadata:
  name: telegram-volume
  namespace: telegram
  labels:
    type: local
spec:
  storageClassName: awifi-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
	
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: telegram
  namespace: telegram
spec:
  storageClassName: awifi-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: Service
apiVersion: v1
metadata:
  name: telegram-svc
  namespace: telegram
  labels:
    app: telegram
spec:
  selector:
    app: telegram
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-dep
  namespace: telegram
  labels:
    app: telegram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram
  template:
    metadata:
      labels:
        app: telegram
    spec:
      containers:
      - name: telegram
        image: awingdev2020/telegram:$BUILD_NUMBER
        env:
        volumeMounts:
        - mountPath: "/db"
          name: telegram
        - mountPath: "/etc/localtime"
          name: awingtimezone
      volumes:
        - name: telegram
          persistentVolumeClaim:
           claimName: telegram
        - name: awingtimezone
          hostPath:
            path: "/usr/share/zoneinfo/Asia/Ho_Chi_Minh"
